- platform: mqtt
  name: "WC, ventilator"
  state_topic: "stat/wc_01/POWER1"
  command_topic: "cmnd/wc_01/POWER1"
  availability_topic: "tele/wc_01/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true