- platform: mqtt
  name: "WC, ventilator"
  state_topic: sonoff-wc/relay/0
  command_topic: sonoff-wc/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-wc/status
  payload_available: 1
  payload_not_available: 0