- alias: Turn off WC fan after 10 minutes
  trigger:
    platform: state
    entity_id: switch.wc_ventilator
    to: 'on'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: switch.wc_ventilator
