homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Apple IOS devices
ios: 

# Display Hass.io config
hassio:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Advertize ports on UPNP
upnp:
  port_mapping: true

# MQTT settings.
mqtt:
  broker: 127.0.0.1
  username: !secret mqtt_user
  password: !secret mqtt_password

# Weather prediction
sensor: !include_dir_merge_list sensors

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches

panel_iframe: !include_dir_merge_list panels

