- platform: mqtt
  name: "Degazman, traka"
  state_topic: "cmnd/degazman_01/POWER"
  command_topic: "cmnd/degazman_01/POWER"
  brightness_state_topic: "cmnd/degazman_01/RESULT"
  brightness_command_topic: "cmnd/degazman_01/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{value_json.Dimmer}}"
  retain: true
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"