- platform: mqtt
  name: "Radna soba, plafon"
  state_topic: "stat/radna_soba_01/POWER2"
  command_topic: "cmnd/radna_soba_01/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Radna soba, traka"
  state_topic: "cmnd/radna_soba_02/POWER"
  command_topic: "cmnd/radna_soba_02/POWER"
  brightness_state_topic: "cmnd/radna_soba_02/RESULT"
  brightness_command_topic: "cmnd/radna_soba_02/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{value_json.Dimmer}}"
  retain: true
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"