- platform: mqtt
  name: "Radna soba, plafon"
  state_topic: "stat/radna_soba_01/POWER2"
  command_topic: "cmnd/radna_soba_01/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true


- platform: mqtt
  name: "Radna soba, traka"
  state_topic: radna_soba_traka/relay/0
  command_topic: radna_soba_traka/relay/0/set
  qos: 1
  retain: true
  payload_on: 1
  payload_off: 0
  availability_topic: radna_soba_traka/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: radna_soba_traka/brightness
  brightness_command_topic: radna_soba_traka/brightness/set
  white_value_state_topic: radna_soba_traka/channel/3
  white_value_command_topic: radna_soba_traka/channel/3/set
  color_temp_command_topic: radna_soba_traka/mired/set

