- name: "Spavaca soba, zid"
  platform: mqtt
  state_topic: sonoff-spavaca-soba/relay/0
  command_topic: sonoff-spavaca-soba/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-spavaca-soba/status
  payload_available: 1
  payload_not_available: 0

# - name: sonoff-spavaca-soba #1
#   platform: mqtt
#   state_topic: sonoff-spavaca-soba/relay/1
#   command_topic: sonoff-spavaca-soba/relay/1/set
#   payload_on: 1
#   payload_off: 0
#   availability_topic: sonoff-spavaca-soba/status
#   payload_available: 1
#   payload_not_available: 0

- platform: mqtt
  name: "Spavaca soba, traka"
  state_topic: spavaca-soba/relay/0
  command_topic: spavaca-soba/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: spavaca-soba/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: spavaca-soba/brightness
  brightness_command_topic: spavaca-soba/brightness/set
  rgb_state_topic: spavaca-soba/rgb
  rgb_command_topic: spavaca-soba/rgb/set
  color_temp_command_topic: spavaca-soba/mired/set
  white_value_state_topic: spavaca-soba/channel/3
  white_value_command_topic: spavaca-soba/channel/3/set

