- alias: "Otisli smo od kuce"
  hide_entity: true
  trigger: 
    platform: state
    entity_id:  group.telefoni
    to: 'not_home'
  action: 
    service: homeassistant.turn_off
    entity_id: group.unutrasnja_svetla
    